// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ExamenParcial2
{
    public partial class TwitterCustomCell : UITableViewCell
    {
        public TwitterCustomCell(IntPtr handle) : base(handle)
        {
        }
        public static readonly NSString Key = new NSString(nameof(TwitterCustomCell));

        #region Properties

        public UIImage ProfileImage
        {
            get => imgProfile.Image;
            set => imgProfile.Image = value;
        }
        public string UserName
        {
            get => lblUser.Text;
            set => lblUser.Text = value;
        }
        public string TweetText
        {
            get => lblTweetInfo.Text;
            set => lblTweetInfo.Text = value;
        }
#endregion
    }
}
