// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace ExamenParcial2
{
	public partial class TwitterTableView : UITableView
	{
		public TwitterTableView (IntPtr handle) : base (handle)
		{
		}
	}
}
